### ISSUE TITLE
app-release_2.1.2.apk can't be installed in Pixel 6

### ISSUE THREAD

**Issue by blguweb** [jins-meme/ES_R-Development-Kit#12]
Excuse me, app-release_2.1.2.apk in release versions can't be installed in Pixel 6(os is 12) which you mentioned that jins meme can directly connect to. Could you provide the correct one？And also, I had tried the other versions and gotten the same result. 
Thanks a lot !

**Comment by tkomde** [comment]
@blguweb 

Can you please try the new version?
I also have a Pixel 6 and can confirm that it is installed and working.
[app-release_2.1.4.apk](https://github.com/jins-meme/ES_R-Development-Kit/releases/download/v2.1.4/app-release_2.1.4.apk)

Also make sure you have the 3rd party APK set to install.

**Comment by blguweb** [comment]
Thanks again! 
I found that I got the JINS MEME not the JINS MEME Academic Pack. What a sad message it is!

Do you know where I can purchase JINS MEME ES_R ？ I only found that JINS MEME  is being sold.

**Comment by tkomde** [comment]
Very sorry. We are not ready for global sales of ES-R at this time. You will need to purchase the product via an import agent.

Wireless certifications are only available in Japan, USA, and China. For other countries, you need to get the wireless certification by yourself.

**Comment by blguweb** [comment]
Thanks for your reply~
