### ISSUE TITLE
License??

### ISSUE THREAD

**Issue by ryohajika** [jins-meme/ES_R-Development-Kit#4]
Hello,
I'm planning to make and publish simple codes for the openFrameworks platform based on this repo. I think it would be great if this repo gets updated with license like MIT, in order to support other contributors. By the way I understand that the compiled libraries (like libDecEnc.a) are confidential so they won't be open-sourced..
Is there any plan to do that?
Also, is it ok to bundle the compiled libraries to my repo on github?
Thank you!

**Comment by tkomde** [comment]
Sorry for the late reply. We've added the SDK license. It is the original license.
